[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"
decorations = "None" #for linux also

opacity = 0.50
blur = true 

option_as_alt = "Both"

[font]
normal.family = "0xProto Nerd font"

size = 14


[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
{ key = "L", mods = "Control|Shift", action = "ToggleMaximized" },
]

 [colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
